version: "1"

services: 
  frontend:
    container_name: frontend_angular
    build: 
      context: '../'
      dockerfile: './docker/frontend-dockerfile'
    port:
      - "8084:8081"
    volumes:
      - ../:/var/www/frontend